# Generated by Django 4.1.4 on 2023-01-01 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0004_alter_libro_autor_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='autor_id',
        ),
        migrations.AddField(
            model_name='libro',
            name='autor_id',
            field=models.ManyToManyField(to='libro.autor'),
        ),
    ]
