# Generated by Django 4.1.4 on 2023-01-01 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0005_remove_libro_autor_id_libro_autor_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='autor',
            name='fecha_creacion',
            field=models.DateField(auto_now=True, verbose_name='Fecha de creación'),
        ),
        migrations.AddField(
            model_name='libro',
            name='fecha_creacion',
            field=models.DateField(auto_now=True, verbose_name='Fecha de creación'),
        ),
    ]
